### PR TITLE
Add strongly typed variant of OnValue

### LINKED ISSUE #465: change Dependency.OnValue<T>(object value) to (T Value)
currently, this overload of OnValue has this definition:

`public static Property OnValue<TDependencyType>(object value);`

wouldn't

`public static Property OnValue<TDependencyType>(`**TDependencyType**` value);`

make more sense? (and catch more bugs via the compiler)

### PR DESCRIPTION
**Pull request by abbotware**
add strongly typed variant of OnValue called OnTypedValue

Fixes #465

### CODE REVIEW

**Comment by jonorossi** [comment]
Closing, code doesn't compile.

**Comment by abbotware** [comment]
what? this did compile at the time i created this...

**Comment by jonorossi** [comment]
> what? this did compile at the time i created this...

It didn't, the AppVeyor build (automatically cleaned up on PR closure) which was timestamped August last year failed, the error in the log was about invalid XML which was likely this:

```
<typeparamref name = "TDependencyType" with type enforcement of the value/>
```

Also you wrote this:

> Disclaimer- I only edited the code on github and not visual studio
> (https://github.com/castleproject/Windsor/issues/465#issuecomment-522534487)

**Comment by abbotware** [comment]
meaning that the C# code was valid... since i copied it from a working method - its just an extension method

**Pull request closed without merging**
