### PR TITLE
ASP.NET Core Facility (made @Inject directive work)

### PR DESCRIPTION
**Pull request by fir3pho3nixx**
Fixed problem whereby registrations had to be doubled up between the application container and the framework container to make @Inject directives work for Razor. This was achieved by registering dependencies as factories in IServiceCollections which resolve back to the IWindsorContainer. IWindsorContainer.Kernel.ComponentRegistered was used to duplicate registrations from Windsor to the IServiceCollection during ConfigureServices(IServiceCollection services). Thanks @generik0 (#389).

### CODE REVIEW

**Comment by generik0** [comment]
Hi i am getting a:


c#```
   at Castle.Facilities.AspNetCore.Resolvers.FrameworkConfigurationDependencyResolver.<>c.<HasMatchingGenericTypesWithoutArguments>b__6_0(ServiceDescriptor x)
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Castle.Facilities.AspNetCore.Resolvers.FrameworkConfigurationDependencyResolver.HasMatchingGenericTypesWithoutArguments(Type dependencyGenericType, List`1 genericServiceTypes)
   at Castle.Facilities.AspNetCore.Resolvers.FrameworkConfigurationDependencyResolver.HasMatchingGenericTypeDefinitions(Type dependencyType)
   at Castle.Facilities.AspNetCore.Resolvers.FrameworkConfigurationDependencyResolver.CanResolve(CreationContext context, ISubDependencyResolver contextHandlerResolver, ComponentModel model, DependencyModel dependency)
   at Castle.MicroKernel.Resolvers.DefaultDependencyResolver.<>c__DisplayClass15_0.<CanResolveFromSubResolvers>b__0(ISubDependencyResolver s)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Castle.MicroKernel.Resolvers.DefaultDependencyResolver.CanResolveFromSubResolvers(CreationContext context, ISubDependencyResolver contextHandlerResolver, ComponentModel model, DependencyModel dependency)
   at Castle.MicroKernel.Resolvers.DefaultDependencyResolver.CanResolve(CreationContext context, ISubDependencyResolver contextHandlerResolver, ComponentModel model, DependencyModel dependency)
   at Castle.MicroKernel.Handlers.AbstractHandler.HasValidComponentFromResolver(DependencyModel dependency)
   at Castle.MicroKernel.Handlers.AbstractHandler.AddResolvableDependency(DependencyModel dependency)
   at Castle.MicroKernel.Handlers.AbstractHandler.AddDependency(DependencyModel dependency)
   at Castle.MicroKernel.Handlers.AbstractHandler.InitDependencies()
   at Castle.MicroKernel.Handlers.DefaultGenericHandler.InitDependencies()
   at Castle.MicroKernel.Handlers.AbstractHandler.Init(IKernelInternal kernel)
   at Castle.MicroKernel.Handlers.DefaultHandlerFactory.Create(ComponentModel model)
   at Castle.MicroKernel.DefaultKernel.Castle.MicroKernel.IKernelInternal.CreateHandler(ComponentModel model)
   at Castle.MicroKernel.DefaultKernel.AddCustomComponent(ComponentModel model)
   at Castle.MicroKernel.Registration.ComponentRegistration`1.Castle.MicroKernel.Registration.IRegistration.Register(IKernelInternal kernel)
   at Castle.MicroKernel.DefaultKernel.Register(IRegistration[] registrations)
   at Castle.MicroKernel.Registration.BasedOnDescriptor.TryRegister(Type type, IKernel kernel)
   at Castle.MicroKernel.Registration.FromDescriptor.Castle.MicroKernel.Registration.IRegistration.Register(IKernelInternal kernel)
   at Castle.MicroKernel.Registration.BasedOnDescriptor.Castle.MicroKernel.Registration.IRegistration.Register(IKernelInternal kernel)
   at Castle.MicroKernel.DefaultKernel.Register(IRegistration[] registrations)
   at Castle.Windsor.WindsorContainer.Register(IRegistration[] registrations)
   at Vem.Common.CastleWindsor.Installers.InstallerTransient.Install(IWindsorContainer container, IConfigurationStore store)
   at Castle.Windsor.Installer.AssemblyInstaller.Install(IWindsorContainer container, IConfigurationStore store)
   at Castle.Windsor.Installer.CompositeInstaller.Install(IWindsorContainer container, IConfigurationStore store)
   at Castle.Windsor.WindsorContainer.Install(IWindsorInstaller[] installers, DefaultComponentInstaller scope)
   at Castle.Windsor.WindsorContainer.Install(IWindsorInstaller[] installers)
   at Vem.Common.CastleWindsor.Extensions.ContainerExtensions.RunInstallers(IWindsorContainer container, Assembly assembly)
   at Vem.Common.CastleWindsor.BootstrapperBase.RunInstallers()
   at Vem.Web.Bootstrapper.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory, IConfigurationRoot configuration)
```

I was not getting this before...

**Comment by generik0** [comment]
Hi @fir3pho3nixx 
After adding the latest facility i can no longer do this:
image

it was working fine before and resolving in runtime. Debug from facility = 
image

**Comment by fir3pho3nixx** [comment]
Definitely not having any problems with it over here: https://github.com/fir3pho3nixx/Windsor.AspNetCore

Can you paste your startup.cs below and a list of your nuget packages so I can try and reproduce it?

**Comment by generik0** [comment]
@fir3pho3nixx It isn't the nuget packages it in internal packages.
Registration done fluently:

```c#
container.Register(Classes.FromAssemblyInThisApplication(EntryAssembly)
                   .Where(t => t.HasNoIocAttributeAndIsNotRegistered(container) 
                    .WithServiceAllInterfaces()
                    .Configure(component =>
                    {
                        component.IsFallback();
                        component.Named($"{component.Implementation.FullName}-Transient");
                    })
                    .WithServiceAllInterfaces()
                    .LifestyleTransient());
```

All i can say it is working before the change. And a null object is being thrown under rgistration

**Comment by generik0** [comment]
Would you like to have a chat about it tomorrow?
I can try to make a good uTest if at all possible without aspnetcore spun up...

**Comment by fir3pho3nixx** [comment]
@generik0 - I have just dropped this in at work and I am not noticing any errors. 

From your screenshots it looks like somehow a ServiceDescriptor is coming through with a ServiceType = null. It is hard to say for sure without a repro.

**Comment by generik0** [comment]
@fir3pho3nixx I can give you access to the full repo. I will drop you an email

**Comment by fir3pho3nixx** [comment]
Sorry @generik0, we found first evidence of torn lifestyles today. This requires more work. I am closing this PR until we get this right. Hope you don’t mind, let’s pursue this on my integration branch.

**Comment by generik0** [comment]
@fir3pho3nixx 
No problem at let me know if you need any help!

**Comment by fir3pho3nixx** [comment]
@jonorossi, both @generik0 and I are “dog fooding” sorry we raised this prematurely. Won’t do it again ;)

**Pull request closed without merging**
