### PR TITLE
GitHub-76 - Fix for XML config parsing error

### PR DESCRIPTION
**Pull request by ChrisM99**
Hello, 
Not sure how to get this fix in to the master repository. 
Please could someone review it?

Thanks

### CODE REVIEW

**Comment by ChrisM99** [comment]
I had a few issues with tabs v spaces in my VS settings, so I reverted the changes and reapplied them. 
It should be good for review now.
Thanks

**Comment by jonorossi** [comment]
@ChrisM99 there are still line ending issues here, could you please resolve them. Could you please also squish your 9 commits to hide all that mess. Thanks.

**Comment by kkozmic** [comment]
For the record, this fixes #76

**Comment by jonorossi** [comment]
Closing this pull request as it has gone very stale.

**Pull request closed without merging**
