### PR TITLE
Refactor build

### PR DESCRIPTION
**Pull request by fir3pho3nixx**
Quick sanity check of #220 before we do this. All comments welcome.

### CODE REVIEW

**Comment by alinapopa** [comment]
Looks good to me

**Comment by jonorossi** [comment]
Looks great! Let's get this merged.

**Comment by hammett** [comment]
So what's the guideline to build Windsor after this PR? I dont want to have VS 2017 and Rider isn't working. Command line seems to work but tests failing (expected?)

**Comment by fir3pho3nixx** [comment]
Without VS2017 you will have issues. Any chance of upgrading? 

I will double check this on Rider. Think my EAP expired so I might have to re-install.

**Comment by fir3pho3nixx** [comment]
Which tests are failing? The WCF stuff wants elevated privs.

**Comment by hammett** [comment]
I dont care for the tests, actually. I just need to be able to build/debug/fix the issues assigned to me, so IDE will be mandatory.

**Comment by fir3pho3nixx** [comment]
Afraid so, we used the new tooling. Sorry!

**Comment by fir3pho3nixx** [comment]
Where have you been @hammett? You've been a little quiet.

**Comment by hammett** [comment]
well, that's not acceptable, is it? The tooling (msbuild) is available to download. 
I kindly ask to do whatever is needed to get this working with Rider. I'm not paying for a license to fix bugs on my spare time.

**Comment by fir3pho3nixx** [comment]
Visual Studio community edition is free. Download that and you should be good to go. It is what I use. I refuse to pay for licenses.

**Comment by hammett** [comment]
In other words, you're saying this is now bound to MS tech?

**Comment by fir3pho3nixx** [comment]
No sir, we are migrating this to linux :)

**Comment by fir3pho3nixx** [comment]
Visual Studio code is also an option ...

**Comment by fir3pho3nixx** [comment]
We just have not finished yet ...

**Comment by fir3pho3nixx** [comment]
You clearly have windows so use this: https://www.visualstudio.com/vs/community/

Night!

**Pull request merged**
