### PR TITLE
Removed silverlight build infrastructure

### PR DESCRIPTION
**Pull request by fir3pho3nixx**
I assumed files with a `*-SL*` pattern to be associated with Silverlight. 

Will hold off on going deeper as you mentioned later on in #165 

Cleaner or no?

### CODE REVIEW

**Comment by jonorossi** [comment]
@fir3pho3nixx looks great! Rename this PR if you are happy for it to be merged.

**Comment by fir3pho3nixx** [comment]
@jonorossi - Good to go!

**Comment by jonorossi** [comment]
Just realised you missed removing the Silverlight lines in `buildscripts/*.nuspec`, need those removed otherwise we'll have a broken build.

**Comment by fir3pho3nixx** [comment]
@jonorossi - All done.

**Comment by jonorossi** [comment]
Great, thanks Gav.

**Pull request merged**
