### PR TITLE
Update basic-tutorial.md

### PR DESCRIPTION
**Pull request by petersmax**
Point references to their proper namespaces and classes.

### CODE REVIEW

**Comment by kkozmic-seek** [comment]
I'd argue that whole tutorial is lacking in quality... Would be nice to give it a proper upgrade.

**Comment by petersmax** [comment]
Agreed but I learned some very basic working stuff so I wouldn't knock it too hard

**Comment by jonorossi** [comment]
@petersmax thanks for the contribution, however I'm not sure why we'd want the tutorial to fully qualify the namespaces of all classes, to me it just makes it look more complicated?

**Comment by petersmax** [comment]
well naturally I would have to agree in that case


____________
Maximus Peters

**Comment by petersmax** [comment]
but would like to note that the namespace references to Component is
ambiguous and it keeps thinking that it is referencing .NET .Component
namespace... as for ClassLibrary it also could not find it either until I
added that.


____________
Maximus Peters

**Pull request merged**
