### PR TITLE
Merge netcore branch to master

### PR DESCRIPTION
**Pull request by fir3pho3nixx**
Merging to master so we can deploy it.

Any final checks we would like to make or add here?

### CODE REVIEW

**Comment by jonorossi** [comment]
I've just diffed the public API and output nuspecs against 3.4.0 and everything looks good.

**Comment by alinapopa** [comment]
I would remove the symbol `DOTNET45`. There is a place that needs it but can be replaced with `NET45`

**Comment by jonorossi** [comment]
> I would remove the symbol DOTNET45. There is a place that needs it but can be replaced with NET45

We can fix that after we merge, there are still a few things left to sort out before releasing.

**Comment by jonorossi** [comment]
Great works guys, not long yet.

**Pull request merged**
