### PR TITLE
Embed icon in NuGet package

### PR DESCRIPTION
**Pull request by generik0**
Remove PackageIconUrl in favour of the new PackageIcon configuration

#518

### CODE REVIEW

**Comment by generik0** [comment]
H @jonorossi looks good so far:

image

image

image

image

**Comment by generik0** [comment]
@jonorossi This is incredibly strange. The AppVeyor build is not adding the icon to the nuspec. Can it be due to the AppVeyor build using an old nuget/VS version?

**Comment by jonorossi** [comment]
> This is incredibly strange. The AppVeyor build is not adding the icon to the nuspec. Can it be due to the AppVeyor build using an old nuget/VS version?

Very possible. We are using VS2017:

https://github.com/castleproject/Windsor/blob/b12304f975ffa832d1df12e4592dbe3e75058380/appveyor.yml#L1

According to [AppVeyor's docs](https://www.appveyor.com/docs/windows-images-software/), it has "NuGet 4.9.2".

**Comment by generik0** [comment]
Can we upgrade to Vs2019? I have not experienced any issues with MSBuild in 2019 vs 2017. All my upgrades went fluently:-)

**Comment by generik0** [comment]
Hi @jonorossi. Sorry about the delay. Busy with work and family. Haven't had the time I needed for anything else (excuses excuses).. 
Now i have the projecticon and projecticonurl in the props

**Comment by jonorossi** [comment]
Thanks

**Pull request merged**
