### PR TITLE
Fixed typed factory out of order disposal

### LINKED ISSUE #114: TypedFactory Disposes Before Component That Depends on it
If a typed factory is a dependency of a disposable component, it is already disposed by the time dispose is called on that component. 

If I directly implement the factory myself rather than using the typed factory, everything behaves as I would expect.

[This SO Question also details the issue](http://stackoverflow.com/questions/34361165/typedfactory-disposes-before-component-using-it-as-a-dependency)

I have attached a test solution below that shows this behavior (although it is not actually useful itself).

[WindsorTypedFactoryDisposalTest.zip](https://github.com/castleproject/Windsor/files/67637/WindsorTypedFactoryDisposalTest.zip)

### PR DESCRIPTION
**Pull request by jnm2**
Fixes #114. See implementation rationale at https://github.com/castleproject/Windsor/issues/114#issuecomment-331667950.

This has been causing no small amount of problems for my company, so hopefully this fix and rationale are adequate.

/cc @fir3pho3nixx @jonorossi

### CODE REVIEW

**Comment by hammett** [comment]
LGTM. I think you deserve some kind of medal for this one, even though the fix is simple, getting there was a brave man's endeavour. Thanks!

**Comment by jnm2** [comment]
@jonorossi Done. The next thing on my mind is, how soon would you consider a hotfix release to NuGet? If worst comes to worst I can build a package myself (your CI artifacts have versions like `0.0.162` which won't be seen as newer than `4.0.0`) but I'd rather not have to worry about that.

**Comment by fir3pho3nixx** [comment]
@jnm2 - The build version if defaulted to zero [here](https://github.com/castleproject/Windsor/blob/master/buildscripts/common.props#L7). What you are seeing is a noddy appveyor counter running in the background which has no relevance to the release. Dev builds only. 

When I worked on porting this project to AppVeyor @jonorossi and I made sure that tag versions for releases flow through to the final published NuGets. Tag = deploy.

If we are following semver than this looks like it will be in a 4.0.1 release.

**Comment by jnm2** [comment]
4.0.1 sounds good. Would you be willing to put at least a prerelease of 4.0.1 on NuGet within a week or so?

**Comment by fir3pho3nixx** [comment]
Faster than that fella! That is why I reworked everything to use appveyor. We have no excuses for releasing early and often anymore :)

Before AppVeyor we used to hoard everything in master with no visibility of the background TeamCity server when merging PR's. 

Your fix is shall we say ... imminent.

**Comment by jonorossi** [comment]
Merged.

@jnm2 @fir3pho3nixx definitely, just need to cut a fresh Castle Core release (https://github.com/castleproject/Core/issues/306) and get Windsor updated to end those assembly binding version problems.

Logged an issue so we can get this version out: https://github.com/castleproject/Windsor/issues/347

**Comment by MishaD87** [comment]
Hello,
I am currently having described problem. I have Castle.Windsor 4.1.1 and Castle.Core 4.3.1.
I have transient module that implements IDisposible and has dependency on typed factory.
Factory creates instances of objects with Singleton life cycle. 
I create objects with factory in my module and trying to release them in Dispose method.
But getting this message "The factory was disposed and can no longer be used"

**Comment by jnm2** [comment]
@MishaD87 Would you be willing to open a new issue and provide the smallest sample code you can which demonstrates this? That'll take a lot of the guesswork out.

**Pull request merged**
