### PR TITLE
Use the latest NUnitTestAdapter for running tests

### PR DESCRIPTION
**Pull request by alinapopa**
Add NUnit3TestAdapter
Use `dotnet test` for running the tests
Upload test results in trx files instead of xml
Fix the error `Could not load file or assembly Microsoft.VisualStudio.TestPlatform.ObjectModel, Version=11.0.0.0` by catching FileNotFoundException in `GetAvailableTypes()`

### CODE REVIEW

**Comment by fir3pho3nixx** [comment]
The only concern I have with doing this is that approach is not yet compatible with linux. 

Please see issue I raised here: https://github.com/nunit/nunit3-vs-adapter/issues/324

**Comment by fir3pho3nixx** [comment]
@alinapopa - Can we close this out and track it with an issue? If we don't do this I can bring TravisCI to Windsor in `refactor-build` with netcore tests running both on windows and linux.

If you agree. Please create a new issue for this and drop it into the planned column and assign me to it. The same problem exists for Castle Core.

**Comment by alinapopa** [comment]
Closing for now; opened issue #243

**Comment by fir3pho3nixx** [comment]
Cool, added NUnit issue tracking link. Thanks.

**Pull request closed without merging**
